_BASE_: "Base-RoIPoly.yaml"
DATALOADER:
  NUM_WORKERS: 12
MODEL:
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3" ]
  SparseRCNN:
    NUM_PROPOSALS: 34
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("crowdai_train",)
  TEST:  ("crowdai_test",)
SOLVER:
  STEPS: (2173795, 2675440)  # drops by a factor of 10 at epoch 65
  MAX_ITER: 2675441  # 80 epochs
  CHECKPOINT_PERIOD: 33443 # the number of images per batch: 33443; annotation_sm_clean_us_index.json: 267542 images in total
  IMS_PER_BATCH: 8
TEST:
  EVAL_PERIOD: 20000000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
