_BASE_: "Base-RoIPoly.yaml"
DATALOADER:
  NUM_WORKERS: 12
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 34
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("aicrowd_train",)
  TEST: ("aicrowd_test",)
SOLVER:
  STEPS: (2006580, 2842655)  # drops by a factor of 10 at epoch 60
  MAX_ITER: 2842656  # 85 epochs
  CHECKPOINT_PERIOD: 33443  # the number of batches per epoch: 33443; annotation_sm_clean_us_index.json: 267542 images in total
  IMS_PER_BATCH: 8
TEST:
  EVAL_PERIOD: 20000000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
